apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-service
  labels:
    app: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: 634115191566.dkr.ecr.us-east-1.amazonaws.com/flag-service:latest
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          env:
            - name: PORT
              value: "8002"
            - name: DATABASE_URL
              value: "postgres://admin:admin123@<RDS_ENDPOINT>:5432/flags_db?sslmode=disable"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.auth-service.svc.cluster.local:8001"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
