apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flag-service-secret
  namespace: flag-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: flag-service-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: flag-service-dev/database-url
